server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roomvacancy
    username: roomvacancy
    password: drowssap
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  application:
    name: ROOM-SERVICE
