server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roomvacancy
    username: roomvacancy
    password: drowssap
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  application:
    name: ADDRESS-SERVICE
